[32mINFO    [0m root:test_allure_fail.py:33 User is entering URL